#myAccountDropMenu  ="xpath://a[@title='My Account']"
                    #"//span[text()='My Account']"
linkloginText          ="xpath://a[text()='Login']"
PrsignupBtn       =   "xpath://a[@href='/login']"
nameTxt         =   "xpath://input[@name='name']"
emailTxt        =   "xpath:(//input[@name='email'])[1]"
newsignupBtn    =   "xpath://button[@data-qa='signup-button']"
passwordTxt     =   "xpath://input[@name='password']"
loginSignupBtn  =   "xpath://a[@href='/login']"
rememCheckBox   =   "xpath://span[@class='aiz-square-check']"
forgotBtn       =   "xpath://a[normalize-space()='Forgot password ?']"
titleCheck      =   "xpath://title[contains(text(),'AT eCommerce | Automation Testing')]"
#notAccountTxt   =   "xpath://div[@role='alert']"
loginBttn       =   "xpath://button[@data-qa='login-button']"
logoutBttn      =   "xpath://a[@href='/logout']"
deletBtnlnk="xpath://a[@href='/delete_account']"
ContBtnlnk="xpath://*[contains(text(),'Continue')]"
