#myAccountDropMenu  ="xpath://a[@title='My Account']"
                    #"//span[text()='My Account']"
CLICK_COOKIE = "xpath://div[@id='cookiescript_accept']"
LOGIN_LINK = "xpath://*[@id='button_tracking-id_login_nav-bar']"
USERNAME_FIELD ="css:input[type=email]"
PASSWORD_FIELD ="css:input[type=password]"
LOGIN_BUTTON = "css:button[type=submit]"
LOGIN_ERROR_MESSAGE = "xpath://div[@class='absolute ml-0 mt-0.5 text-red-500 text-sm truncate inset-x-0']"
# PAGE_TITLE = (By.CSS_SELECTOR, ".e-form-heading")
PAGE_TITLE = "xpath://head"
FORGOT_PASSWORD_LINK = "css:[href='https://app.involve.me/password/reset']"
#LOGIN_LINK = "xpath://*[@id='button_tracking-id_login_nav-bar']"
ACCOUNT_DROP_DOWN_MENU = "css:#nav-dropdown"
LOGOUT_BTN = "css:[href='https://app.involve.me/logout']"
LOGINUSER = "xpath://div[@data-intercom-target='project-overview-workspaces-header']/span"

#
# linkloginText          ="xpath://a[text()='Login']"
# signupBtn       =   "xpath://a[@href='/login']"
# nameTxt         =   "xpath://input[@name='name']"
# emailTxt        =   "xpath:(//input[@name='email'])[1]"
# newsignupBtn    =   "xpath://button[@data-qa='signup-button']"
# passwordTxt     =   "xpath://input[@name='password']"
# loginSignupBtn  =   "xpath://a[@href='/login']"
# rememCheckBox   =   "xpath://span[@class='aiz-square-check']"
# forgotBtn       =   "xpath://a[normalize-space()='Forgot password ?']"
# titleCheck      =   "xpath://title[contains(text(),'AT eCommerce | Automation Testing')]"
# #notAccountTxt   =   "xpath://div[@role='alert']"
# loginBttn       =   "xpath://button[@data-qa='login-button']"
# logoutBttn      =   "xpath://a[@href='/logout']"
# deletBtnlnk="xpath://a[@href='/delete_account']"
# ContBtnlnk="xpath://*[contains(text(),'Continue')]"
